name: connectivity_repository
description: Un repositorio de Flutter para manejar la conectividad de red.
version: 1.0.4
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  connectivity_plus: ^7.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.10.4
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^10.0.0
